package main

// 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.
func findTheDifference(s string, t string) byte {
    var result byte

    for i := 0; i < len(s); i++{
        result ^= s[i]
        result ^= t[i]
    }

    result ^= t[len(t)-1]

    return result
}
